import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyState,validateState,cleanRecord,mergeStates,daysLeft,addDays,filterRecords,mergedRecords,makeSamples,safeURL} from '../site/core.js';
const manual=cleanRecord({id:'manual:test',title:'실제 수동 입력',deadline:'2026-12-31',eligibility:['예비창업자'],category:'창업·사업화'});
test('date boundaries and leap years',()=>{assert.equal(daysLeft('2026-01-01','2025-12-31'),1);assert.equal(addDays('2024-02-28',1),'2024-02-29');assert.throws(()=>cleanRecord({...manual,deadline:'2026-02-30'}));assert.throws(()=>cleanRecord({...manual,start:'2027-01-01'}));});
test('backup roundtrip, merge, and preserve existing manual records',()=>{const current=emptyState();current.manual=[manual];const incoming=emptyState();incoming.manual=[{...manual,id:'manual:second'}];incoming.tracking[manual.id]={favorite:true,status:'지원 준비',note:'개인 메모'};incoming.snapshots[manual.id]=manual;const next=mergeStates(current,validateState(JSON.parse(JSON.stringify(incoming))));assert.equal(next.manual.length,2);assert.equal(next.tracking[manual.id].note,'개인 메모');assert.equal(current.manual.length,1);});
test('reject unsafe or malformed backups before saving',()=>{assert.equal(safeURL('javascript:alert(1)'),'');assert.equal(safeURL('https://user:pass@example.com'),'');assert.throws(()=>cleanRecord({...manual,url:'javascript:alert(1)'}));assert.throws(()=>validateState({version:2}));const s=emptyState();s.tracking['__proto__:x']={};assert.throws(()=>validateState(s));});
test('saved official records survive a new feed without them',()=>{const official={...manual,id:'bizinfo:PBLN_123',source:'bizinfo'};const state=emptyState();state.snapshots[official.id]=official;assert.equal(mergedRecords([],state,[])[0].archived,true);assert.equal(mergedRecords([official],state,[]).length,1);assert.equal(mergedRecords([official],state,[])[0].archived,undefined);});
test('sample opt-in and combined filters',()=>{const s=emptyState(),samples=makeSamples('2026-10-08');assert.equal(mergedRecords([],s,samples).length,0);s.demo=true;assert.equal(mergedRecords([],s,samples).length,9);s.tracking[manual.id]={favorite:true,status:'지원 준비',note:''};assert.equal(filterRecords([manual],{query:'수동',category:'창업·사업화',eligibility:'예비창업자',status:'지원 준비',page:'favorites',hideClosed:true,today:'2026-10-08'},s.tracking).length,1);assert.equal(filterRecords([manual],{query:'없는 공고'},s.tracking).length,0);});
